/**
 * report.js — turn a simulation result into a Markdown report or a JSON bundle
 * that can be re-imported.
 */

const MODE_LABEL = {
  detection: 'Deadlock detection (wait-for graph + cycle detection)',
  prevention: 'Deadlock prevention (timestamp ordering)',
  bankers: "Deadlock avoidance (Banker's algorithm)",
  game: 'Scheduler game',
};

function lockTableMd(lockTable) {
  const rows = Object.entries(lockTable || {});
  if (!rows.length) return '_empty_';
  return ['| Resource | Holders | Waiting |', '|---|---|---|']
    .concat(rows.map(([res, e]) => `| ${res} | ${e.holders.map((h) => `${h.txn}(${h.mode})`).join(', ') || '—'} | ${e.queue.map((q) => `${q.txn}(${q.mode})`).join(', ') || '—'} |`))
    .join('\n');
}

/**
 * @param {{title?:string, mode:string, input:object, result:{steps:object[], summary:object, options?:object}}} run
 */
export function toMarkdown(run) {
  const { mode, input, result } = run;
  const lines = [];
  lines.push(`# Deadlock Game report — ${run.title || MODE_LABEL[mode] || mode}`);
  lines.push('');
  lines.push(`- **Mode:** ${MODE_LABEL[mode] || mode}`);
  if (result.options) lines.push(`- **Options:** ${Object.entries(result.options).map(([k, v]) => `${k} = ${v}`).join(', ')}`);
  lines.push(`- **Generated:** ${new Date(run.createdAt || Date.now()).toLocaleString()}`);
  lines.push('');
  lines.push('## Input');
  lines.push('');
  if (input.schedule) {
    lines.push('```');
    lines.push(input.schedule);
    lines.push('```');
  } else if (input.available) {
    lines.push(`Available: \`${input.available}\``);
    lines.push('');
    lines.push('Max:');
    lines.push('```\n' + input.max + '\n```');
    lines.push('Allocation:');
    lines.push('```\n' + input.allocation + '\n```');
    if (input.request && input.request.vector) lines.push(`Request: P${input.request.pid} → \`${input.request.vector}\``);
  }
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  for (const [k, v] of Object.entries(result.summary || {})) {
    lines.push(`- **${k}:** ${Array.isArray(v) ? v.join(', ') || '—' : typeof v === 'object' && v ? JSON.stringify(v) : String(v)}`);
  }
  lines.push('');
  lines.push('## Step-by-step trace');
  lines.push('');
  (result.steps || []).forEach((s) => {
    lines.push(`### Step ${s.index + 1}: ${s.explanation?.title || s.event}`);
    lines.push('');
    if (s.op?.text) lines.push(`Operation: \`${s.op.text}\``);
    lines.push('');
    lines.push(s.explanation?.text || '');
    if (s.explanation?.why) lines.push(`\n> **Why it matters:** ${s.explanation.why}`);
    if (s.cycle) lines.push(`\n**Cycle:** ${s.cycle.join(' → ')}`);
    if (s.wfg && s.wfg.edges.length) lines.push(`\n**Wait-for edges:** ${s.wfg.edges.map((e) => `${e.from} → ${e.to} (${e.res})`).join(', ')}`);
    if (s.lockTable) { lines.push('\n**Lock table:**\n'); lines.push(lockTableMd(s.lockTable)); }
    if (s.state) {
      lines.push(`\nWork = [${(s.state.work || s.state.available).join(', ')}]  Finish = [${(s.state.finish || []).map((f) => (f ? 'T' : 'F')).join(', ')}]`);
    }
    lines.push('');
  });
  lines.push('---');
  lines.push('_Generated by Deadlock Game — DBMS course project._');
  return lines.join('\n');
}

export function toJSON(run) {
  return JSON.stringify({ version: 1, app: 'deadlock-game', ...run }, null, 2);
}

/** Validate an imported JSON bundle. */
export function fromJSON(text) {
  let data;
  try { data = JSON.parse(text); } catch { throw new Error('File is not valid JSON.'); }
  if (!data || data.app !== 'deadlock-game' || !data.mode || !data.input) throw new Error('Not a Deadlock Game export file.');
  return { mode: data.mode, input: data.input, title: data.title || '' };
}
